server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: Worker-Management-Service
          uri: lb://Worker-Management-Service
          predicates:
            - Path=/api/v1/worker-management/**
        - id: Payment-Service
          uri: lb://Payment-Service
          predicates:
            - Path=/api/v1/payment-service/**
        - id: Entity-Service
          uri: lb://Entity-Service
          predicates:
            - Path=/api/v1/entity/**


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost